FROM node:24-slim AS builder

WORKDIR /build

COPY package*.json .

RUN npm ci --omit=dev

COPY . .

ENV NEXT_PUBLIC_API_BASE_URL="https://pmonger.shubhampanjiyara.blog/api"
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="dvln1dlk4"

RUN npm run build



FROM nginx:1.29.3 AS runner

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /build/dist /usr/share/nginx/html 

EXPOSE 80

CMD [ "nginx","-g","daemon off;" ]




